version: 1.0.{build}

image: Visual Studio 2019

platform:
  - x64

before_build:
 
  - git clone https://github.com/TsioryRasoloarijaona/amortissement_windows_version.git C:\projects_2\amortissement-windows-version
  - cd C:\projects\amortissement-windows-version

 
  - del /f /q C:\projects_2\amortissement-windows-version\CMakeCache.txt
  - rmdir /s /q C:\projects_2\amortissement-windows-version\build


  - mkdir C:\projects_2\amortissement-windows-version\build
  - cd C:\projects_2\amortissement-windows-version\build


  - cmake -DCMAKE_TOOLCHAIN_FILE=toolchain-mingw.cmake -DCMAKE_PREFIX_PATH="C:\Qt\6.8.1\mingw_64\lib\cmake\Qt6" -G "MinGW Makefiles" ..

build_script:
  - cd C:\projects_2\amortissement-windows-version\build
  - mingw32-make

artifacts:
  - path:  C:\projects_2\amortissement-windows-version\build\amortissement_app.exe
    name: executable
